### ISSUE TITLE
Do you have any plans to make this PCL compatible?

### ISSUE THREAD

**Issue by rossdargan** [SparkDustJoe/miniLockManaged#4]
I started my own port then found this! I'm pretty sure everything up to key gen can be made PCL (that's where I go to) except perhaps Zxcvdn.dll - I couldn't find a c# port of that.

What's your feeling for the rest - I suspect it should port pretty nicely.

Happy to do a pull and start contributing if you want?

Ta

Ross

**Comment by SparkDustJoe** [comment]
Sorry for the delay, I didn't get a notification on this issue.  I'm not familiar enough with PCL to say one way or another.   Michael Ford has a C# port of Zxcvdn which I haven't pulled the source out of, I just use the compiled version.  Somewhere in my documentation there is a link to his Repo.

-Dustin
